FROM alpine:3.22

RUN apk add --no-cache\
	php82\
	php82-fpm\
	php82-mysqli\
	php82-json\
	php82-curl\
	php82-dom\
	php82-exif\
	php82-fileinfo\
	php82-mbstring\
	php82-openssl\
	php82-xml\
	php82-zip\
	wget\
	curl

RUN mkdir -p /run/php && chmod 755 /run/php

WORKDIR /var/www/html

COPY ./tools/script.sh /usr/local/bin/script.sh
RUN chmod +x /usr/local/bin/script.sh

CMD ["/usr/local/bin/script.sh"]
	
